// import './i18n/config'
export { Canvas } from './components/Canvas/Canvas'
export { Magnifier } from './components/Magnifier'
export { useColorPicker } from './context/hook'
export { ColorPickerProvider } from './context/provider'
